// <auto-generated/>
// Generated by Arrow.SourceGenerator. Do not edit.
#nullable enable

namespace Golden.Adapters
{
    /// <summary>
    /// Apache Arrow mapping generated for <see cref="global::Golden.Adapters.AdapterEvent"/>.
    /// </summary>
    public static partial class AdapterEventArrow
    {
        /// <summary>
        /// The Apache Arrow schema of <see cref="global::Golden.Adapters.AdapterEvent"/>: one field per mapped member,
        /// in field order. Built once and shared; Apache.Arrow schemas are immutable.
        /// </summary>
        public static global::Apache.Arrow.Schema Schema { get; } = CreateSchema();

        private static global::Apache.Arrow.Schema CreateSchema()
        {
            var fields = new global::Apache.Arrow.Field[]
            {
                new global::Apache.Arrow.Field("Sku", global::Apache.Arrow.Types.Int32Type.Default, nullable: false),
                new global::Apache.Arrow.Field("Replaces", global::Apache.Arrow.Types.Int32Type.Default, nullable: true),
                new global::Apache.Arrow.Field("Label", global::Apache.Arrow.Types.StringType.Default, nullable: false),
                new global::Apache.Arrow.Field("Alias", global::Apache.Arrow.Types.StringType.Default, nullable: true),
                new global::Apache.Arrow.Field("At", global::Apache.Arrow.Types.Int64Type.Default, nullable: false),
            };
            return new global::Apache.Arrow.Schema(fields, null);
        }

        /// <summary>
        /// Converts <paramref name="rows"/> into one <c>RecordBatch</c> with <see cref="global::Golden.Adapters.AdapterEvent"/>'s
        /// <see cref="Schema"/>. An empty collection produces a valid zero-length batch.
        /// </summary>
        /// <param name="rows">The rows. Enumerated once per field; must not change meanwhile.</param>
        /// <returns>A new batch that owns its buffers; the caller disposes it.</returns>
        /// <exception cref="global::System.ArgumentException">A row is null, a non-nullable
        /// reference member is null, or a value does not fit its Arrow type.</exception>
        /// <exception cref="global::System.InvalidOperationException">The collection changed while
        /// it was being converted.</exception>
        public static global::Apache.Arrow.RecordBatch ToRecordBatch(global::System.Collections.Generic.IReadOnlyCollection<global::Golden.Adapters.AdapterEvent> rows)
        {
            if (rows is null) throw new global::System.ArgumentNullException(nameof(rows));
            return BuildRecordBatch(rows, rows.Count);
        }

        /// <summary>
        /// Converts a sequence of <see cref="global::Golden.Adapters.AdapterEvent"/> into consecutive batches of at most
        /// <paramref name="batchSize"/> rows. Lazy: each batch is built as it is requested, and
        /// an empty sequence yields no batches.
        /// </summary>
        /// <param name="rows">The rows, enumerated once.</param>
        /// <param name="batchSize">The maximum rows per batch; at least 1.</param>
        /// <returns>Batches the caller owns and disposes.</returns>
        public static global::System.Collections.Generic.IEnumerable<global::Apache.Arrow.RecordBatch> ToRecordBatches(global::System.Collections.Generic.IEnumerable<global::Golden.Adapters.AdapterEvent> rows, int batchSize)
        {
            if (rows is null) throw new global::System.ArgumentNullException(nameof(rows));
            if (batchSize < 1) throw new global::System.ArgumentOutOfRangeException(nameof(batchSize), batchSize, "batchSize must be at least 1.");
            return ToRecordBatchesIterator(rows, batchSize);
        }

        private static global::System.Collections.Generic.IEnumerable<global::Apache.Arrow.RecordBatch> ToRecordBatchesIterator(global::System.Collections.Generic.IEnumerable<global::Golden.Adapters.AdapterEvent> rows, int batchSize)
        {
            var chunk = new global::System.Collections.Generic.List<global::Golden.Adapters.AdapterEvent>(global::System.Math.Min(batchSize, 1024));
            global::Apache.Arrow.RecordBatch batch;
            foreach (var row in rows)
            {
                chunk.Add(row);
                if (chunk.Count == batchSize)
                {
                    batch = BuildRecordBatch(chunk, chunk.Count);
                    chunk.Clear();
                    yield return batch;
                }
            }
            if (chunk.Count > 0)
            {
                batch = BuildRecordBatch(chunk, chunk.Count);
                chunk.Clear();
                yield return batch;
            }
        }

        private static global::Apache.Arrow.RecordBatch BuildRecordBatch(global::System.Collections.Generic.IReadOnlyCollection<global::Golden.Adapters.AdapterEvent> rows, int count)
        {
            var columns = new global::Apache.Arrow.IArrowArray[5];
            try
            {
                columns[0] = BuildColumn_Sku(rows, count);
                columns[1] = BuildColumn_Replaces(rows, count);
                columns[2] = BuildColumn_Label(rows, count);
                columns[3] = BuildColumn_Alias(rows, count);
                columns[4] = BuildColumn_At(rows, count);
                return new global::Apache.Arrow.RecordBatch(Schema, columns, count);
            }
            catch
            {
                foreach (var column in columns)
                {
                    column?.Dispose();
                }
                throw;
            }
        }

        // Sku: Int32
        private static global::Apache.Arrow.IArrowArray BuildColumn_Sku(global::System.Collections.Generic.IReadOnlyCollection<global::Golden.Adapters.AdapterEvent> rows, int count)
        {
            var values = new global::Apache.Arrow.ArrowBuffer.Builder<int>(count);
            int index = 0;
            foreach (var row in rows)
            {
                if (index >= count) ThrowCollectionChanged();
                if (row is null) ThrowNullRow(index);
                var value = Store_Sku(row, index);
                values.Append(value);
                index++;
            }
            if (index != count) ThrowCollectionChanged();
            var data = new global::Apache.Arrow.ArrayData(Schema.FieldsList[0].DataType, count, 0, 0, new[] { global::Apache.Arrow.ArrowBuffer.Empty, values.Build() });
            return global::Apache.Arrow.ArrowArrayFactory.BuildArray(data);
        }

        // Sku: stored through global::Golden.Adapters.SkuAdapter
        private static int Store_Sku(global::Golden.Adapters.AdapterEvent row, int index)
        {
            return global::Golden.Adapters.SkuAdapter.ToStorage(row.Sku);
        }

        // Replaces: Int32
        private static global::Apache.Arrow.IArrowArray BuildColumn_Replaces(global::System.Collections.Generic.IReadOnlyCollection<global::Golden.Adapters.AdapterEvent> rows, int count)
        {
            var values = new global::Apache.Arrow.ArrowBuffer.Builder<int>(count);
            var validity = new global::Apache.Arrow.ArrowBuffer.BitmapBuilder(count);
            int nulls = 0;
            int index = 0;
            foreach (var row in rows)
            {
                if (index >= count) ThrowCollectionChanged();
                if (row is null) ThrowNullRow(index);
                if (Store_Replaces(row, index) is { } value)
                {
                    values.Append(value);
                    validity.Append(true);
                }
                else
                {
                    values.Append(default(int));
                    validity.Append(false);
                    nulls++;
                }
                index++;
            }
            if (index != count) ThrowCollectionChanged();
            var data = new global::Apache.Arrow.ArrayData(Schema.FieldsList[1].DataType, count, nulls, 0, new[] { nulls == 0 ? global::Apache.Arrow.ArrowBuffer.Empty : validity.Build(), values.Build() });
            return global::Apache.Arrow.ArrowArrayFactory.BuildArray(data);
        }

        // Replaces: stored through global::Golden.Adapters.SkuAdapter
        private static int? Store_Replaces(global::Golden.Adapters.AdapterEvent row, int index)
        {
            return row.Replaces is { } domain ? (int?)global::Golden.Adapters.SkuAdapter.ToStorage(domain) : null;
        }

        // Label: Utf8
        private static global::Apache.Arrow.IArrowArray BuildColumn_Label(global::System.Collections.Generic.IReadOnlyCollection<global::Golden.Adapters.AdapterEvent> rows, int count)
        {
            var builder = new global::Apache.Arrow.StringArray.Builder();
            builder.Reserve(count);
            int index = 0;
            foreach (var row in rows)
            {
                if (index >= count) ThrowCollectionChanged();
                if (row is null) ThrowNullRow(index);
                if (Store_Label(row, index) is { } value)
                {
                    builder.Append(value);
                }
                else
                {
                    ThrowRequiredNull(index, "Label");
                }
                index++;
            }
            if (index != count) ThrowCollectionChanged();
            return builder.Build();
        }

        // Label: stored through global::Golden.Adapters.TagAdapter
        private static string Store_Label(global::Golden.Adapters.AdapterEvent row, int index)
        {
            if (row.Label is { } domain) return global::Golden.Adapters.TagAdapter.ToStorage(domain);
            ThrowRequiredNull(index, "Label");
            return default!;
        }

        // Alias: Utf8
        private static global::Apache.Arrow.IArrowArray BuildColumn_Alias(global::System.Collections.Generic.IReadOnlyCollection<global::Golden.Adapters.AdapterEvent> rows, int count)
        {
            var builder = new global::Apache.Arrow.StringArray.Builder();
            builder.Reserve(count);
            int index = 0;
            foreach (var row in rows)
            {
                if (index >= count) ThrowCollectionChanged();
                if (row is null) ThrowNullRow(index);
                if (Store_Alias(row, index) is { } value)
                {
                    builder.Append(value);
                }
                else
                {
                    builder.AppendNull();
                }
                index++;
            }
            if (index != count) ThrowCollectionChanged();
            return builder.Build();
        }

        // Alias: stored through global::Golden.Adapters.TagAdapter
        private static string? Store_Alias(global::Golden.Adapters.AdapterEvent row, int index)
        {
            return row.Alias is { } domain ? (string?)global::Golden.Adapters.TagAdapter.ToStorage(domain) : null;
        }

        // At: Int64
        private static global::Apache.Arrow.IArrowArray BuildColumn_At(global::System.Collections.Generic.IReadOnlyCollection<global::Golden.Adapters.AdapterEvent> rows, int count)
        {
            var values = new global::Apache.Arrow.ArrowBuffer.Builder<long>(count);
            int index = 0;
            foreach (var row in rows)
            {
                if (index >= count) ThrowCollectionChanged();
                if (row is null) ThrowNullRow(index);
                var value = Store_At(row, index);
                values.Append(value);
                index++;
            }
            if (index != count) ThrowCollectionChanged();
            var data = new global::Apache.Arrow.ArrayData(Schema.FieldsList[4].DataType, count, 0, 0, new[] { global::Apache.Arrow.ArrowBuffer.Empty, values.Build() });
            return global::Apache.Arrow.ArrowArrayFactory.BuildArray(data);
        }

        // At: stored through global::Golden.Adapters.UnixSeconds
        private static long Store_At(global::Golden.Adapters.AdapterEvent row, int index)
        {
            return global::Golden.Adapters.UnixSeconds.ToStorage(row.At);
        }

        /// <summary>
        /// Materialises every row of <paramref name="batch"/> as <see cref="global::Golden.Adapters.AdapterEvent"/>.
        /// Fields are matched by name, so extra fields and field order do not matter.
        /// </summary>
        /// <param name="batch">The batch. It is read, never retained or disposed.</param>
        /// <exception cref="global::System.IO.InvalidDataException">The batch does not match
        /// <see cref="Schema"/> (every mismatch is listed), is structurally malformed, or holds a
        /// value outside the range of its CLR type.</exception>
        public static global::Golden.Adapters.AdapterEvent[] FromRecordBatch(global::Apache.Arrow.RecordBatch batch)
        {
            if (batch is null) throw new global::System.ArgumentNullException(nameof(batch));
            return ReadRecordBatch(batch);
        }

        /// <summary>
        /// Materialises the rows of each batch in turn, lazily. Each batch is validated when it
        /// is reached; batches are read, never retained or disposed.
        /// </summary>
        /// <param name="batches">The batches, enumerated once.</param>
        public static global::System.Collections.Generic.IEnumerable<global::Golden.Adapters.AdapterEvent> FromRecordBatches(global::System.Collections.Generic.IEnumerable<global::Apache.Arrow.RecordBatch> batches)
        {
            if (batches is null) throw new global::System.ArgumentNullException(nameof(batches));
            return FromRecordBatchesIterator(batches);
        }

        private static global::System.Collections.Generic.IEnumerable<global::Golden.Adapters.AdapterEvent> FromRecordBatchesIterator(global::System.Collections.Generic.IEnumerable<global::Apache.Arrow.RecordBatch> batches)
        {
            foreach (var batch in batches)
            {
                if (batch is null) throw new global::System.ArgumentException("The batch sequence contains a null batch.", nameof(batches));
                foreach (var row in ReadRecordBatch(batch))
                {
                    yield return row;
                }
            }
        }

        private static global::Golden.Adapters.AdapterEvent[] ReadRecordBatch(global::Apache.Arrow.RecordBatch batch)
        {
            int[] ordinals = ResolveColumns(batch);
            var c0 = (global::Apache.Arrow.Int32Array)batch.Column(ordinals[0]);
            global::System.ReadOnlySpan<int> v0 = c0.Values;
            var c1 = (global::Apache.Arrow.Int32Array)batch.Column(ordinals[1]);
            global::System.ReadOnlySpan<int> v1 = c1.Values;
            var c2 = (global::Apache.Arrow.StringArray)batch.Column(ordinals[2]);
            var c3 = (global::Apache.Arrow.StringArray)batch.Column(ordinals[3]);
            var c4 = (global::Apache.Arrow.Int64Array)batch.Column(ordinals[4]);
            global::System.ReadOnlySpan<long> v4 = c4.Values;
            int length = batch.Length;
            var rows = new global::Golden.Adapters.AdapterEvent[length];
            for (int i = 0; i < length; i++)
            {
                rows[i] = new global::Golden.Adapters.AdapterEvent() { Sku = global::Golden.Adapters.SkuAdapter.FromStorage(v0[i]), Replaces = c1.IsNull(i) ? null : (global::Golden.Adapters.Sku?)global::Golden.Adapters.SkuAdapter.FromStorage(v1[i]), Label = global::Golden.Adapters.TagAdapter.FromStorage(c2.GetString(i)!), Alias = c3.IsNull(i) ? null : global::Golden.Adapters.TagAdapter.FromStorage(c3.GetString(i)!), At = global::Golden.Adapters.UnixSeconds.FromStorage(v4[i]) };
            }
            return rows;
        }

        /// <summary>
        /// Checks every assumption the reader makes about <paramref name="batch"/> and returns the
        /// column ordinal of each field. Throws once, listing every problem found.
        /// </summary>
        internal static int[] ResolveColumns(global::Apache.Arrow.RecordBatch batch)
        {
            var ordinals = new int[5];
            global::System.Collections.Generic.List<string>? errors = null;

            // Sku
            {
                int index = FindField(batch, "Sku", ref errors);
                ordinals[0] = index;
                if (index >= 0)
                {
                    global::Apache.Arrow.IArrowArray column = batch.Column(index);
                    string? problem = CheckColumnShape(batch, index, column, global::Apache.Arrow.Types.ArrowTypeId.Int32, "Int32")
                        ?? CheckFixedWidth(column, sizeof(int))
                        ?? (column.NullCount > 0 ? "is non-nullable but holds " + column.NullCount + " null value(s)" : null)
                        ;
                    if (problem is not null) AddError(ref errors, "Sku", problem);
                }
            }

            // Replaces
            {
                int index = FindField(batch, "Replaces", ref errors);
                ordinals[1] = index;
                if (index >= 0)
                {
                    global::Apache.Arrow.IArrowArray column = batch.Column(index);
                    string? problem = CheckColumnShape(batch, index, column, global::Apache.Arrow.Types.ArrowTypeId.Int32, "Int32")
                        ?? CheckFixedWidth(column, sizeof(int))
                        ;
                    if (problem is not null) AddError(ref errors, "Replaces", problem);
                }
            }

            // Label
            {
                int index = FindField(batch, "Label", ref errors);
                ordinals[2] = index;
                if (index >= 0)
                {
                    global::Apache.Arrow.IArrowArray column = batch.Column(index);
                    string? problem = CheckColumnShape(batch, index, column, global::Apache.Arrow.Types.ArrowTypeId.String, "Utf8")
                        ?? CheckOffsets((global::Apache.Arrow.BinaryArray)column)
                        ?? (column.NullCount > 0 ? "is non-nullable but holds " + column.NullCount + " null value(s)" : null)
                        ;
                    if (problem is not null) AddError(ref errors, "Label", problem);
                }
            }

            // Alias
            {
                int index = FindField(batch, "Alias", ref errors);
                ordinals[3] = index;
                if (index >= 0)
                {
                    global::Apache.Arrow.IArrowArray column = batch.Column(index);
                    string? problem = CheckColumnShape(batch, index, column, global::Apache.Arrow.Types.ArrowTypeId.String, "Utf8")
                        ?? CheckOffsets((global::Apache.Arrow.BinaryArray)column)
                        ;
                    if (problem is not null) AddError(ref errors, "Alias", problem);
                }
            }

            // At
            {
                int index = FindField(batch, "At", ref errors);
                ordinals[4] = index;
                if (index >= 0)
                {
                    global::Apache.Arrow.IArrowArray column = batch.Column(index);
                    string? problem = CheckColumnShape(batch, index, column, global::Apache.Arrow.Types.ArrowTypeId.Int64, "Int64")
                        ?? CheckFixedWidth(column, sizeof(long))
                        ?? (column.NullCount > 0 ? "is non-nullable but holds " + column.NullCount + " null value(s)" : null)
                        ;
                    if (problem is not null) AddError(ref errors, "At", problem);
                }
            }

            if (errors is not null)
            {
                throw new global::System.IO.InvalidDataException("The RecordBatch does not match the generated Arrow schema of " + "AdapterEvent" + ": " + string.Join("; ", errors) + ".");
            }
            return ordinals;
        }

        /// <summary>
        /// Validates <paramref name="batch"/> against <see cref="global::Golden.Adapters.AdapterEvent"/>'s <see cref="Schema"/>,
        /// exactly as <see cref="FromRecordBatch"/> does, and returns a typed view over it without
        /// copying. The view is valid for as long as the batch is.
        /// </summary>
        /// <param name="batch">The batch. It is not retained beyond the view, nor disposed.</param>
        /// <exception cref="global::System.IO.InvalidDataException">The batch does not match.</exception>
        public static AdapterEventArrowView View(global::Apache.Arrow.RecordBatch batch)
        {
            if (batch is null) throw new global::System.ArgumentNullException(nameof(batch));
            return new AdapterEventArrowView(batch);
        }

        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
        private static void ThrowCollectionChanged()
        {
            throw new global::System.InvalidOperationException("The row collection changed while it was being converted: it no longer yields Count rows.");
        }

        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
        private static void ThrowNullRow(int index)
        {
            throw new global::System.ArgumentException("Row " + index + " is null; " + "AdapterEvent" + " rows must not be null.", "rows");
        }

        [global::System.Diagnostics.CodeAnalysis.DoesNotReturn]
        private static void ThrowRequiredNull(int index, string field)
        {
            throw new global::System.ArgumentException("Row " + index + ": the value for non-nullable Arrow field '" + field + "' is null.", "rows");
        }

        private static int FindField(global::Apache.Arrow.RecordBatch batch, string name, ref global::System.Collections.Generic.List<string>? errors)
        {
            int found = -1;
            int matches = 0;
            var fields = batch.Schema.FieldsList;
            for (int i = 0; i < fields.Count; i++)
            {
                if (string.Equals(fields[i].Name, name, global::System.StringComparison.Ordinal))
                {
                    found = i;
                    matches++;
                }
            }
            if (matches == 1) return found;
            AddError(ref errors, name, matches == 0 ? "is missing" : "appears " + matches + " times, so it is ambiguous");
            return -1;
        }

        private static void AddError(ref global::System.Collections.Generic.List<string>? errors, string field, string problem)
        {
            (errors ??= new global::System.Collections.Generic.List<string>()).Add("field '" + field + "' " + problem);
        }

        private static string? CheckColumnShape(global::Apache.Arrow.RecordBatch batch, int index, global::Apache.Arrow.IArrowArray column, global::Apache.Arrow.Types.ArrowTypeId expected, string expectedName)
        {
            global::Apache.Arrow.Types.IArrowType type = column.Data.DataType;
            if (type.TypeId == global::Apache.Arrow.Types.ArrowTypeId.Dictionary) return "is dictionary-encoded, which is not supported; decode it first";
            if (type.TypeId == global::Apache.Arrow.Types.ArrowTypeId.Extension) return "has an extension type, which is not supported; expected " + expectedName;
            if (type.TypeId != expected) return "expected " + expectedName + ", found " + type.Name;
            if (batch.Schema.FieldsList[index].DataType.TypeId != type.TypeId) return "is declared as " + batch.Schema.FieldsList[index].DataType.Name + " by the schema but its column holds " + type.Name;
            if (column.Length != batch.Length) return "has " + column.Length + " values but the batch has " + batch.Length + " rows";
            return null;
        }

        private static string? CheckValidity(global::Apache.Arrow.ArrayData data)
        {
            long bits = (long)data.Offset + data.Length;
            if (data.Offset < 0 || data.Length < 0) return "has a negative offset or length";
            if (data.Buffers.Length == 0) return "has no buffers";
            global::Apache.Arrow.ArrowBuffer validity = data.Buffers[0];
            if (data.NullCount > 0 && validity.IsEmpty) return "declares nulls but has no validity bitmap";
            if (!validity.IsEmpty && validity.Length < (bits + 7) / 8) return "has a validity bitmap shorter than its length";
            if (!validity.IsEmpty && data.NullCount >= 0)
            {
                global::System.ReadOnlySpan<byte> map = validity.Span;
                long unset = 0;
                for (long i = data.Offset; i < bits; i++)
                {
                    if ((map[(int)(i >> 3)] & (1 << (int)(i & 7))) == 0) unset++;
                }
                if (unset != data.NullCount) return "declares " + data.NullCount + " null value(s) but its validity bitmap marks " + unset;
            }
            return null;
        }

        // byteWidth 0 means bit-packed (Boolean).
        private static string? CheckFixedWidth(global::Apache.Arrow.IArrowArray column, int byteWidth)
        {
            global::Apache.Arrow.ArrayData data = column.Data;
            string? problem = CheckValidity(data);
            if (problem is not null) return problem;
            if (data.Buffers.Length < 2) return "is missing its value buffer";
            long end = (long)data.Offset + data.Length;
            long needed = byteWidth == 0 ? (end + 7) / 8 : end * byteWidth;
            return data.Buffers[1].Length < needed ? "has a value buffer of " + data.Buffers[1].Length + " bytes where " + needed + " are required" : null;
        }

        private static string? CheckOffsets(global::Apache.Arrow.BinaryArray array)
        {
            global::Apache.Arrow.ArrayData data = array.Data;
            string? problem = CheckValidity(data);
            if (problem is not null) return problem;
            if (data.Buffers.Length < 3) return "is missing its offset or value buffer";
            long slots = (long)data.Offset + data.Length + 1;
            if (data.Buffers[1].Length < slots * 4) return "has an offset buffer shorter than its length";
            global::System.ReadOnlySpan<int> offsets = array.ValueOffsets;
            int valuesLength = array.ValueBuffer.Length;
            int previous = offsets[0];
            if (previous < 0 || previous > valuesLength) return "has an offset outside its value buffer at slot 0";
            for (int k = 1; k < offsets.Length; k++)
            {
                int offset = offsets[k];
                if (offset < previous || offset > valuesLength) return "has offsets that decrease or run past its value buffer at slot " + (k - 1);
                previous = offset;
            }
            return null;
        }

        private static global::System.IO.InvalidDataException OutOfRange(int row, string field, string clrType, global::System.Exception? inner = null)
        {
            return new global::System.IO.InvalidDataException("Row " + row + ": the value in Arrow field '" + field + "' is outside the range of " + clrType + ".", inner);
        }
    }

    /// <summary>
    /// A validated, strongly typed view over a <c>RecordBatch</c> of <see cref="global::Golden.Adapters.AdapterEvent"/>:
    /// one Apache.Arrow array per field, resolved once, with no copy. Obtain one from
    /// <see cref="AdapterEventArrow.View"/>. It does not own the batch.
    /// </summary>
    public sealed partial class AdapterEventArrowView
    {
        internal AdapterEventArrowView(global::Apache.Arrow.RecordBatch batch)
        {
            if (batch is null) throw new global::System.ArgumentNullException(nameof(batch));
            int[] ordinals = AdapterEventArrow.ResolveColumns(batch);
            Batch = batch;
            Sku = (global::Apache.Arrow.Int32Array)batch.Column(ordinals[0]);
            Replaces = (global::Apache.Arrow.Int32Array)batch.Column(ordinals[1]);
            Label = (global::Apache.Arrow.StringArray)batch.Column(ordinals[2]);
            Alias = (global::Apache.Arrow.StringArray)batch.Column(ordinals[3]);
            At = (global::Apache.Arrow.Int64Array)batch.Column(ordinals[4]);
        }

        /// <summary>The batch this view reads.</summary>
        public global::Apache.Arrow.RecordBatch Batch { get; }

        /// <summary>The number of rows.</summary>
        public int Length => Batch.Length;

        /// <summary>Arrow field <c>Sku</c> (Int32).</summary>
        public global::Apache.Arrow.Int32Array Sku { get; }

        /// <summary>Arrow field <c>Replaces</c> (Int32, nullable).</summary>
        public global::Apache.Arrow.Int32Array Replaces { get; }

        /// <summary>Arrow field <c>Label</c> (Utf8).</summary>
        public global::Apache.Arrow.StringArray Label { get; }

        /// <summary>Arrow field <c>Alias</c> (Utf8, nullable).</summary>
        public global::Apache.Arrow.StringArray Alias { get; }

        /// <summary>Arrow field <c>At</c> (Int64).</summary>
        public global::Apache.Arrow.Int64Array At { get; }
    }
}
