// <auto-generated/>
// Generated by Arrow.SourceGenerator. Do not edit.
#nullable enable

namespace Golden.@namespace
{
    partial class Outer
    {
        /// <summary>
        /// Apache Arrow mapping generated for <see cref="global::Golden.@namespace.Outer.KeywordAndEscaping"/>.
        /// </summary>
        public static partial class KeywordAndEscapingArrow
        {
        }
    }
}
