// <auto-generated/>
// Generated by Arrow.SourceGenerator. Do not edit.
#nullable enable

namespace Golden.Events
{
    /// <summary>
    /// Apache Arrow mapping generated for <see cref="global::Golden.Events.ScalarEvent"/>.
    /// </summary>
    public static partial class ScalarEventArrow
    {
    }
}
