using Arrow.SourceGenerator.Model;

namespace Arrow.SourceGenerator.Emit;

/// <summary>
/// Writes the generated file for one target: the file header, the namespace and containing-type
/// scopes, and the companion type. Capability emitters fill the companion as they land.
/// </summary>
internal static class ArrowEmitter
{
    public const string HintSuffix = ".Arrow.g.cs";

    public static string HintName(TargetModel model) =>
        SourceNames.HintName(model.HintIdentity, HintSuffix);

    public static string Emit(TargetModel model)
    {
        var writer = new SourceWriter();
        writer.Line("// <auto-generated/>");
        writer.Line("// Generated by Arrow.SourceGenerator. Do not edit.");
        writer.Line("#nullable enable");
        writer.Line();

        SourceWriter.Scope? ns =
            model.Namespace.Length > 0
                ? writer.Block("namespace " + SourceNames.DottedIdentifier(model.Namespace))
                : null;

        var containers = new SourceWriter.Scope[model.ContainingTypes.Count];
        for (int i = 0; i < model.ContainingTypes.Count; i++)
        {
            ContainingTypeModel outer = model.ContainingTypes[i];
            containers[i] = writer.Block(
                $"partial {Keyword(outer.Kind)} {SourceNames.Identifier(outer.Name)}"
            );
        }

        EmitCompanion(writer, model);

        for (int i = containers.Length - 1; i >= 0; i--)
        {
            containers[i].Dispose();
        }

        ns?.Dispose();
        return writer.ToString();
    }

    private static void EmitCompanion(SourceWriter writer, TargetModel model)
    {
        writer.Line("/// <summary>");
        writer.Line(
            $"/// Apache Arrow mapping generated for <see cref=\"{model.FullyQualifiedName}\"/>."
        );
        writer.Line("/// </summary>");
        using (
            writer.Block(
                $"{model.Accessibility} static partial class {SourceNames.Identifier(model.CompanionName)}"
            )
        ) { }
    }

    private static string Keyword(TargetKind kind) =>
        kind switch
        {
            TargetKind.Struct => "struct",
            TargetKind.RecordClass => "record",
            TargetKind.RecordStruct => "record struct",
            TargetKind.Interface => "interface",
            _ => "class",
        };
}
