using Arrow.SourceGenerator.Tests.Infrastructure;
using Shouldly;
using Xunit;

namespace Arrow.SourceGenerator.Tests;

/// <summary>
/// The API-surface renderer is itself a gate, so its rules are tested before any generated code
/// depends on them.
/// </summary>
public sealed class GeneratedApiSurfaceTests
{
    private const string Sample = """
        // <auto-generated />
        #nullable enable
        namespace Demo
        {
            public static partial class OrderArrow
            {
                private static readonly global::System.Int32 _cache = 1;
                public static global::System.String Name { get; } = "";
                public static int Convert(global::System.Collections.Generic.IReadOnlyCollection<int> rows, int batchSize = 4) => 0;
                internal static void Hidden() { }
                private sealed class Helper
                {
                    public void NotApi() { }
                }
            }

            public sealed class OrderArrowView
            {
                internal OrderArrowView() { }
                public int Length { get; }
                public string? Label { get; internal set; }
            }

            internal static class Internal
            {
                public static void NotApi() { }
            }
        }
        """;

    [Fact]
    public void BaselineListsOnlyExternallyReachableSignaturesInOrdinalOrder()
    {
        GeneratedApiSurface
            .CreateBaseline(Sample)
            .ShouldBe(
                """
                #nullable enable
                Demo.OrderArrowView.Label.get -> string?
                Demo.OrderArrowView.Length.get -> int
                sealed Demo.OrderArrowView
                static Demo.OrderArrow
                static Demo.OrderArrow.Convert(System.Collections.Generic.IReadOnlyCollection<int> rows, int batchSize = 4) -> int
                static Demo.OrderArrow.Name.get -> System.String

                """.Replace("\r\n", "\n", StringComparison.Ordinal)
            );
    }

    [Fact]
    public void ShapeSummaryCountsTypesMembersAndParameterSlots()
    {
        GeneratedApiSurface
            .CreateShapeSummary(Sample)
            .ShouldBe("# generated API shape summary\nTYPES=2 MEMBERS=4 PARAMETERS=2\n");
    }

    [Fact]
    public void ReopenedPartialContainersAreTransparent()
    {
        const string nested =
            "namespace N { partial class Outer { public static partial class InnerArrow { public static int X => 1; } } }";

        GeneratedApiSurface
            .CreateBaseline(nested)
            .ShouldBe(
                "#nullable enable\nstatic N.Outer.InnerArrow\nstatic N.Outer.InnerArrow.X.get -> int\n"
            );
    }

    [Fact]
    public void RenderingIsIndependentOfDeclarationOrder()
    {
        const string forwards = "namespace N { public class A { public int X; public int Y; } }";
        const string backwards = "namespace N { public class A { public int Y; public int X; } }";

        GeneratedApiSurface
            .CreateBaseline(forwards)
            .ShouldBe(GeneratedApiSurface.CreateBaseline(backwards));
    }
}
